  root: true
  extends:
    - '@gitlab'
  parserOptions:
    parser: babel-eslint
  rules:
    filenames/match-regex:
    - error
    - "^[a-z_]+(\\.config|\\.documentation|\\.[a-z_]+\\.example|\\.spec)?$"
    import/no-extraneous-dependencies: off
