extends:
  - '@gitlab'
parserOptions:
  parser: babel-eslint
overrides:
  files:
    - rollup.config.js
    - stories/*.js
    - stories/**/*.js
    - components/**/*.documentation.js
  rules:
    # We deactive the match-regex rule due to our documentation files having the naming convention
    # <component_name>.documentation.js
    filenames/match-regex: off
    import/no-extraneous-dependencies: off
