image: node:latest

stages:
    - build
    - test
    - deploy
    - release

visual:
  stage: test
  script:
    - sh ./ci-scripts/workaround-puppeteer-issue-290.sh
    - yarn install
    - yarn test
  artifacts:
    when: always
    paths:
      - tests/__image_snapshots__/

update_snapshots:
  stage: build
  when: manual
  script:
    - sh ./ci-scripts/workaround-puppeteer-issue-290.sh
    - yarn install
    - yarn test --updateSnapshot
    - git config --global user.email "gitlab-bot@gitlab.com"
    - git config --global user.name "GitLab Bot"
    - git add .
    - git commit -m "Update snapshots"
    - git push https://gitlab-bot:$GITLAB_BOT_TOKEN@gitlab.com/gitlab-org/frontend/gitlab-ui.git HEAD:$CI_COMMIT_REF_NAME &>/dev/null

pages:
  stage: deploy
  script:
    - yarn install
    - yarn storybook-static
    - mkdir public
    - mv storybook/* public
  artifacts:
    paths:
      - public
  only:
    - master

publish:
  stage: release
  when: manual
  script:
    - yarn install
    - $(yarn bin)/rollup -c
    - semantic-release
  only:
    - master
