variables:
  PUPPETEER_VERSION: "1.11.0"
  PUPPETEER_IMAGE: $CI_REGISTRY_IMAGE/puppeteer:$PUPPETEER_VERSION

stages:
    - pre-build
    - build-and-check
    - deploy
    - release

.yarn_install:
  image: $PUPPETEER_IMAGE
  before_script:
    - yarn install

build_docker_image:
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  image: docker:stable
  stage: pre-build
  script:
    - "mkdir -p ~/.docker"
    - >
      echo '{"experimental": "enabled"}' > ~/.docker/config.json
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./build-docker.sh

build:
  extends: .yarn_install
  stage: build-and-check
  script:
    - yarn storybook-static
    - mkdir public
    - mv storybook/* public
  artifacts:
    paths:
      - public

lint:
  extends: .yarn_install
  dependencies: []
  stage: build-and-check
  script:
    - yarn lint
    - yarn prettier --list-different '**/*.{js,vue}'

visual:
  extends: .yarn_install
  tags:
    - gitlab-org # This allows us to use higher performance runners
  dependencies: []
  stage: build-and-check
  script:
    - yarn test
  artifacts:
    when: always
    paths:
      - tests/__image_snapshots__/

update_snapshots:
  extends: .yarn_install
  tags:
    - gitlab-org # This allows us to use higher performance runners
  stage: pre-build
  when: manual
  script:
    - yarn test --updateSnapshot
    - git config --global user.email "gitlab-bot@gitlab.com"
    - git config --global user.name "GitLab Bot"
    - git add .
    - git commit -m "Update snapshots"
    - git push https://gitlab-bot:$GITLAB_TOKEN@gitlab.com/gitlab-org/gitlab-ui.git HEAD:$CI_COMMIT_REF_NAME &>/dev/null

review:
  stage: deploy
  dependencies:
    - build
  script:
    - rsync -av --delete public /srv/nginx/pages/$CI_COMMIT_REF_SLUG
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://$CI_COMMIT_REF_SLUG.$APPS_DOMAIN
    on_stop: review_stop
  only:
    - branches@gitlab-org/gitlab-ui
  except:
    - master
  tags:
    - nginx
    - review-apps
    - deploy

review_stop:
  dependencies: []
  stage: deploy
  script:
    - rm -rf public /srv/nginx/pages/$CI_COMMIT_REF_SLUG
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - branches@gitlab-org/gitlab-ui
  except:
    - master
  tags:
    - nginx
    - review-apps
    - deploy

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo "Deploying to Pages"
  artifacts:
    paths:
      - public
  only:
    - master

upload_artifacts:
  extends: .yarn_install
  stage: release
  dependencies: []
  script:
    - yarn build
    - yarn pack --filename gitlab-ui.$CI_COMMIT_REF_SLUG.tgz
    - echo "The package.json dependency URL is https://gitlab.com/gitlab-org/gitlab-ui/-/jobs/$CI_JOB_ID/artifacts/raw/gitlab-ui.$CI_COMMIT_REF_SLUG.tgz"
  artifacts:
    when: always
    paths:
      - gitlab-ui.$CI_COMMIT_REF_SLUG.tgz

publish:
  extends: .yarn_install
  stage: release
  dependencies: []
  script:
    - yarn build
    - $(yarn bin)/semantic-release
  only:
    - master
